MONGODB_HOST: mongodb-{{ env }}.ramvelcheti.store # mongodb-dev.daws86s.fun
REDIS_HOST: redis-{{ env }}.ramvelcheti.store
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.ramvelcheti.store
CART_HOST: cart.backend-alb-{{ env }}.ramvelcheti.store
USER_HOST: user.backend-alb-{{ env }}.ramvelcheti.store
RABBITMQ_HOST: rabbitmq-{{ env }}.ramvelcheti.store
MYSQL_HOST: mysql-{{ env }}.ramvelcheti.store
SHIPPING_HOST: shipping.backend-alb-{{ env }}.ramvelcheti.store
PAYMENT_HOST: payment.backend-alb-{{ env }}.ramvelcheti.store
