MONGODB_HOST: mongodb-{{ env }}.ramvlecheti.store
REDIS_HOST: redis-{{ env }}.ramvelcheti.store
CATALOGUE_HOST: catalogue-{{ env }}.ramvelcheti.store
CART_HOST: cart-{{ env }}.ramvelcheti.store
MYSQL_HOST: mysql-{{ env }}.ramvelcheti.store
SHIPPING_HOST: shipping-{{ env }}.ramvelcheti.store
USER_HOST: user-{{ env }}.ramvelcheti.store
RABBITMQ_HOST: rabbitmq-{{ env }}.ramvelcheti.store
PAYMENT_HOST: payment-{{ env }}.ramvelcheti.store